/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panel.SubMusicPanel;

import javax.swing.JLabel;
import javax.swing.JPanel;
import views.MainFrame;

/**
 *
 * @author linhd
 */
public class SongMusicPanel extends javax.swing.JPanel {

    /**
     * Creates new form SongMusicPanel
     * @param frame
     */
    public SongMusicPanel(MainFrame frame) {
        initComponents();    
        
    }

    public JPanel getAdd_playlist() {
        return add_playlist;
    }
    public void setTextName(String name) {
        this.name_song.setText(name);
    }

    public void setSinger(String singer) {
        this.singer.setText(singer);
    }    

    public JLabel getName_song() {
        return name_song;
    }

    public JPanel getPlay() {
        return play;
    }

    public JLabel getSinger() {
        return singer;
    }

    public JPanel getMenu() {
        return optional_list;
    }
    
        
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_song = new javax.swing.JLabel();
        singer = new javax.swing.JLabel();
        add_playlist = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        optional_list = new javax.swing.JPanel();
        play = new javax.swing.JPanel();
        play_btn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        name_song.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name_song.setForeground(new java.awt.Color(255, 255, 255));
        name_song.setText("Anh ta bỏ em rồi");

        singer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        singer.setForeground(new java.awt.Color(255, 255, 255));
        singer.setText("Hương Giang");

        add_playlist.setBackground(new java.awt.Color(0, 0, 0));

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_18px_3.png"))); // NOI18N

        javax.swing.GroupLayout add_playlistLayout = new javax.swing.GroupLayout(add_playlist);
        add_playlist.setLayout(add_playlistLayout);
        add_playlistLayout.setHorizontalGroup(
            add_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_playlistLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        add_playlistLayout.setVerticalGroup(
            add_playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_playlistLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(add))
        );

        optional_list.setBackground(new java.awt.Color(204, 204, 204));
        optional_list.setForeground(new java.awt.Color(255, 255, 255));
        optional_list.setOpaque(false);

        javax.swing.GroupLayout optional_listLayout = new javax.swing.GroupLayout(optional_list);
        optional_list.setLayout(optional_listLayout);
        optional_listLayout.setHorizontalGroup(
            optional_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        optional_listLayout.setVerticalGroup(
            optional_listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        play.setBackground(new java.awt.Color(0, 0, 0));
        play.setOpaque(false);

        play_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_play_18px.png"))); // NOI18N

        javax.swing.GroupLayout playLayout = new javax.swing.GroupLayout(play);
        play.setLayout(playLayout);
        playLayout.setHorizontalGroup(
            playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(play_btn))
        );
        playLayout.setVerticalGroup(
            playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(play_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(name_song, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(singer, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(add_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(optional_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optional_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(add_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name_song)
                                .addComponent(singer))
                            .addGap(15, 15, 15)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JPanel add_playlist;
    private javax.swing.JLabel name_song;
    private javax.swing.JPanel optional_list;
    private javax.swing.JPanel play;
    private javax.swing.JLabel play_btn;
    private javax.swing.JLabel singer;
    // End of variables declaration//GEN-END:variables
    
}
