/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panel;

import controllers.PlayingController;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import models.Playlist;
import models.User;
import views.MainFrame;
import views.panel.SubPlaylistPanel.SubPlaylistEmptyPanel;
import views.panel.SubPlaylistPanel.SubPlaylistPanel;

/**
 *
 * @author linhd
 */
public class MyPlayListPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyPlayList
     * @param frame
     * @param playlists
     */
    public MyPlayListPanel(User user, MainFrame frame, ArrayList<Playlist> playlists) {
        initComponents();
        setLayout(new BorderLayout());
                
        JScrollPane sp = new JScrollPane(createPanel(user, frame, playlists));
        add(sp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(41, 41, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private JPanel createPanel(User user, MainFrame frame, ArrayList<Playlist> playlists) {
        JPanel panel = new JPanel();
        
        int cols = 4;
        int rows = Math.round((float)playlists.size() / cols);
        
        if (rows < 3) 
            rows = 3;
        panel.setLayout(new GridLayout(rows, cols, 0, 0));
        
        for (int i = 0; i < cols * rows; ++i) {
            if (i < playlists.size()) {
                SubPlaylistPanel spp = new SubPlaylistPanel(user,frame, null, playlists.get(i), i);
                panel.add(spp);                                   
            } else {     
                SubPlaylistEmptyPanel emptyPanel = new SubPlaylistEmptyPanel();
                panel.add(emptyPanel);
            }
        }
        return panel;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
