/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panel;

import controllers.ViewController;
import controllers.ListPanelController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import models.Singer;
import views.MainFrame;
import views.panel.SubSingerPanel.SubSingerPanel;

/**
 *
 * @author linhd
 */
public class SingerPanel extends javax.swing.JPanel {

    /**
     * Creates new form testSingerPanel
     * @param frame
     */
    public SingerPanel(MainFrame frame, ArrayList<Singer> listSinger) {
        initComponents();
        setLayout(new BorderLayout());
        JScrollPane sc = new JScrollPane(createListArtist(frame, listSinger));       
        add(sc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();

        main.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
    private static JPanel createListArtist(MainFrame frame, ArrayList<Singer> listSinger) {
       JPanel panel = new JPanel();
        ArrayList <SubSingerPanel> list = new ArrayList<>();
        for (Singer singer : listSinger) {
            SubSingerPanel s = new SubSingerPanel(frame);
            s.setArtist_name(singer.getName());
            s.setCountry(singer.getCountry());            
            list.add(s);              
        }                         
        panel.setLayout(new GridLayout(list.size(), 1, 0, 0)); 
        
        for (int i = 0; i < list.size(); ++i) {
            Singer singer = listSinger.get(i);
            
            SubSingerPanel p1 = list.get(i);            
            if (i % 2 == 0) 
                p1.setBackground(new Color(41, 41, 39));            
            panel.add(p1);
            
            // add event list panel
            ListPanelController spc = new ListPanelController(frame, p1);
            spc.init();
            
            // add event click panel 
            p1.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    ViewController cvc = new ViewController(frame);
                    try {
                        cvc.setSingerDetail(singer);
                    } catch (SQLException ex) {
                        Logger.getLogger(SingerPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            
            // add general event scroll panel

        } 
        
        return panel;
    }
}
