/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import DatabaseQuery.UserQuery;
import controllers.AudioController;
import javax.swing.JOptionPane;
import controllers.FileController;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javazoom.jlgui.basicplayer.BasicPlayer;
import models.Account;
import models.User;

/**
 *
 * @author pytha
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     * @param user
     */
    public LoginForm(User user) {
        
        
        this.setTitle("Sign In");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocation(400, 200);
        initComponents();
        
        AudioController audio = AudioController.getIntance();
        if (!audio.isStop()) {
            audio.stop();
        }
        
        
        if (user != null) {
            txtUser.setText(user.getUsername());
            txtUser.setForeground(Color.black);
            txtPass.setText(user.getPassword());
            txtPass.setForeground(Color.black);
        }
        
        addTextEvent(this);
        
        sign_in.addMouseListener(new EventForm(this));
        sign_up.addMouseListener(new EventForm(this));       
        
        setVisible(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        chkSave = new javax.swing.JCheckBox();
        sign_in = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        unk = new javax.swing.JLabel();
        sign_up = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setBackground(new java.awt.Color(153, 255, 255));
        title.setForeground(new java.awt.Color(153, 255, 51));

        title_label.setBackground(new java.awt.Color(51, 255, 51));
        title_label.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("Music Player");
        title_label.setOpaque(true);

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(title_label)
                .addContainerGap())
        );

        main.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel2.setText("Password");

        jLabel5.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        jLabel5.setText("User");

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setText("Username");

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(204, 204, 204));
        txtPass.setText("Password");

        chkSave.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        chkSave.setText("Remember me");

        sign_in.setBackground(new java.awt.Color(0, 204, 51));
        sign_in.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sign_in.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sign_in.setText("Sign In");
        sign_in.setOpaque(true);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addGap(25, 25, 25)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(chkSave)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSave)
                    .addComponent(sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        unk.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        unk.setText("If you didn't have an account. Just ");

        sign_up.setBackground(new java.awt.Color(0, 204, 51));
        sign_up.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sign_up.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sign_up.setText("Sign up");
        sign_up.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(unk)
                .addGap(61, 61, 61)
                .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unk)
                    .addComponent(sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel main;
    private javax.swing.JLabel sign_in;
    private javax.swing.JLabel sign_up;
    private javax.swing.JPanel title;
    private javax.swing.JLabel title_label;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel unk;
    // End of variables declaration//GEN-END:variables

    
    private void addTextEvent(LoginForm form) {
        
        txtUser.addKeyListener(new KeyAdapter() {
            
            @Override
            public void keyTyped(KeyEvent e) {               
                if (e.getKeyChar() == KeyEvent.VK_ENTER) {
                    try {
                        getLogin(form);
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                String str = txtUser.getText().trim();
                switch (str) {
                    case "Username":
                        txtUser.setText("");
                        txtUser.setForeground(Color.black);
                        txtUser.setCaretPosition(0);
                        break;
                    case "":
                        txtUser.setText("Username");
                        txtUser.setForeground(new Color(204, 204, 204));
                        break;
                    default:
                        txtUser.setForeground(Color.black);
                        break;
                }
                
            }
            
        });
        
        txtPass.addKeyListener(new KeyAdapter() {            
            @Override
            public void keyTyped(KeyEvent e) {
                if (e.getKeyChar() == KeyEvent.VK_ENTER) {
                    try {
                        getLogin(form);
                    } catch (SQLException ex) {
                        Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                String str = String.valueOf(txtPass.getPassword()).trim();
                switch (str) {
                    case "Password":
                        txtPass.setText("");
                        txtPass.setForeground(Color.black);
                        txtPass.setCaretPosition(0);
                        break;
                    case "":
                        txtPass.setText("Password");
                        txtPass.setForeground(new Color(204, 204, 204));
                        break;
                    default:
                        txtPass.setForeground(Color.black);
                        break;
                }
                
            }
        });
    }
  
    private class EventForm extends MouseAdapter {
        
        private LoginForm loginForm;
        
        public EventForm() {
            
        }

        public EventForm(LoginForm loginForm) {
            this.loginForm = loginForm;
        }
        
        @Override
        public void mouseEntered(MouseEvent e) {
            JLabel lb = (JLabel) e.getSource();
            
            lb.setBackground(new Color(0, 255, 51));
        } 
        
        @Override
        public void mouseExited(MouseEvent e) {
            JLabel lb = (JLabel) e.getSource();
            lb.setBackground(new Color(0, 204, 51));
        }
        
        @Override
        public void mouseClicked(MouseEvent e) {
            JLabel lb = (JLabel) e.getSource();
            if (lb.equals(sign_in)) {
                try {
                    getLogin(loginForm);
                } catch (SQLException ex) {
                    Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                loginForm.dispose();
                SignUpForm form = new SignUpForm();
                form.setVisible(true);
            }
        }

        
        
        
    }
    private User getUser(String username, String password) { 
        
            UserQuery query = new UserQuery();
            
            User user = query.getUser(username, password);
            
            return user;
        }
    private void getLogin(LoginForm form) throws SQLException {
            String username = txtUser.getText().trim();
            String password = String.valueOf(txtPass.getPassword()).trim();
            
            if (username.equals("") || password.equals("")) {
                JOptionPane.showMessageDialog(null, "Không để trống username, password");
                return;
            }
            User user = getUser(username, password);
            if (user == null) {
                JOptionPane.showMessageDialog(main, "Thông tin người dùng không chính xác");
            } else {
                if (chkSave.isSelected()) {
                    Account acc = new Account(user.getUsername(), user.getPassword());
                    FileController.saveData(acc, "acc.txt");
                }
                form.dispose();                
                MainFrame frame = new MainFrame(user);                
                frame.setVisible(true);
            }
        }
    
}
