/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panel.SubSearchPanel;

/**
 *
 * @author linhd
 */
public class SubTitlePanel extends javax.swing.JPanel {

    /**
     * Creates new form SongTitlePanel
     */
    public SubTitlePanel(String title) {
        initComponents();
        this.title.setText(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlesong = new javax.swing.JPanel();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));

        titlesong.setBackground(new java.awt.Color(102, 102, 102));

        title.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Bài hát >");

        javax.swing.GroupLayout titlesongLayout = new javax.swing.GroupLayout(titlesong);
        titlesong.setLayout(titlesongLayout);
        titlesongLayout.setHorizontalGroup(
            titlesongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlesongLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(title)
                .addGap(0, 0, 0))
        );
        titlesongLayout.setVerticalGroup(
            titlesongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlesongLayout.createSequentialGroup()
                .addComponent(title)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(titlesong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titlesong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel title;
    private javax.swing.JPanel titlesong;
    // End of variables declaration//GEN-END:variables
    public void setTitle(String title) {
        this.title.setText(title);
    }
}
