/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panel.SubSingerPanel;

import javax.swing.JLabel;
import views.MainFrame;

/**
 *
 * @author linhd
 */
public class SubSingerPanel extends javax.swing.JPanel {

    /**
     * Creates new form subAtistPanel
     */
    public SubSingerPanel(MainFrame frame) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        artist_name = new javax.swing.JLabel();
        country = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        artist_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        artist_name.setForeground(new java.awt.Color(255, 255, 255));
        artist_name.setText("Đen vâu");

        country.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        country.setForeground(new java.awt.Color(255, 255, 255));
        country.setText("Việt Nam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(artist_name, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artist_name)
                    .addComponent(country))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artist_name;
    private javax.swing.JLabel country;
    // End of variables declaration//GEN-END:variables
    
    public JLabel getArtist_name() {
        return artist_name;
    }

    public void setArtist_name(String artist_name) {
        this.artist_name.setText(artist_name);
    }

    public String getCountry() {
        return country.getText();
    }

    public void setCountry(String country) {
        this.country.setText(country);
    }
    
}
