/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.panel.SubSingerPanel;

import javax.swing.JLabel;

/**
 *
 * @author linhd
 */
public class TitleSingerDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form TitleSingerDetailPanel
     */
    public TitleSingerDetailPanel() {
        initComponents();
    }
    
    public String getCountry() {
        return country.getText();
    }

    public void setCountry(String country) {
        this.country.setText(country);
    }

    public String getDob() {
        return dob.getText();
    }

    public void setDob(String dob) {
        this.dob.setText(dob);
    }

    public String getNamee() {
        return name.getText();
    }

    public void setNamee(String name) {
        this.name.setText(name);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("Ái Phương");

        country.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        country.setForeground(new java.awt.Color(255, 255, 255));
        country.setText("Việt Nam");

        dob.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dob.setForeground(new java.awt.Color(255, 255, 255));
        dob.setText("11/02/1999");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel country;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
